-- Create table for Team
CREATE TABLE IF NOT EXISTS team (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    country VARCHAR(255) NOT NULL,
    city VARCHAR(255) NOT NULL,
    annual_budget DECIMAL(15, 2) NOT NULL,
    commission DOUBLE PRECISION NOT NULL
);

-- Create table for Player
CREATE TABLE IF NOT EXISTS player (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    age INT NOT NULL CHECK (age >= 16),
    salary DECIMAL(12, 2) NOT NULL CHECK (salary >= 0.00),
    experience_months INT NOT NULL CHECK (experience_months >= 0),
    market_value DECIMAL(12, 2) NOT NULL CHECK (market_value >= 0.00),
    team_id BIGINT NOT NULL,
    FOREIGN KEY (team_id) REFERENCES team(id) ON DELETE CASCADE
);